### ISSUE TITLE
support for 21

### ISSUE THREAD

**Issue by tsloughter** [project-fifo/rebar_erl_vsn#1]
Should HEAD be set to 21? opencensus failed to build on erlang master because of this plugin crashing.

**Comment by Licenser** [comment]
It sure shouldn't crash. Can you share the output of `rebar_api:get_arch(),` on HEAD?

Regarding setting it to 21 I'm not sure about that, given that there is no way knowing what version of head it is. But I'm kind of curious what the output is and how much info we can get from it :)

**Comment by tsloughter** [comment]
```
rebar_api:get_arch().
"21.0-rc0-x86_64-unknown-linux-gnu-64"
```

And the crash was:

```
===> Provider: {default,erl_vsn}
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump
===> Uncaught error: function_clause
===> Stack trace to the error location:
[{rebar_erl_vsn_prv,enumerate,
                    [{21,0},[]],
                    [{file,"/home/tristan/Devel/vonnegut/_build/default/plugins/rebar_erl_vsn/src/rebar_erl_vsn_prv.erl"},
                     {line,51}]},
 {rebar_erl_vsn_prv,do,1,
                    [{file,"/home/tristan/Devel/vonnegut/_build/default/plugins/rebar_erl_vsn/src/rebar_erl_vsn_prv.erl"},
                     {line,27}]},
```

**Comment by Licenser** [comment]
Awesome thanks! As you already have the trouble can you give the `unknown-vsn` branch a go it should solve the problem for good. I rather have a solution to handle 'this erlang is knower then what the plugin knows' then just pumbling it to 21 w/o adding the required `-defines` for 21 (I must admit I'm not sure which are required :( )

**Comment by Licenser** [comment]
http://www.erlang.org/news/115 seems not to include any major changes that require -defines to work over multiple versions. it seems to be save to add 21 in addition to the fix in unknown vsn

**Comment by tsloughter** [comment]
Close:

```
 Provider: erl_vsn
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump
===> Uncaught error: badarg
===> Stack trace to the error location:
[{io,format,
     [<0.52.0>,
      "\e[0;35m===> The erlang version ~p.~p is newer then the latest version known to rebar_erl_vsn (~p). Features introduced between after ~p will not have flags.~n\e[0m",
      [21,20,20]],
     []},
 {rebar_erl_vsn_prv,enumerate,2,
                    [{file,"/home/tristan/Devel/elli_date/_build/default/plugins/rebar_erl_vsn/src/rebar_erl_vsn_prv.erl"},
                     {line,55}]},
```

**Comment by Licenser** [comment]
I wish I could count to 4 :joy:

**Comment by Licenser** [comment]
okay that should do it, sorry for the patch ping-pong and abusing you to test it ;)

**Comment by tsloughter** [comment]
hehe, no worries. And yup, it does work now :)

**Comment by Licenser** [comment]
awesome thanks! I'll push thins (and add 21) as 0.1.4
