### ISSUE TITLE
The tag name is confused

### ISSUE THREAD

**Issue by getong** [project-fifo/rebar_erl_vsn#5]
As Kyorai/riak_core#34, rebar3_erl_vsn 0.2.0 tag does not handle the `ssl_accept_deprecated` option.
~Need a new tag.~
why 0.1.9 is the later version, and 0.2.0 is the older version. Very confused.

**Comment by Licenser** [comment]
I honestly am not sure, that was an issue w/ the rebar3 hex plugin I guess. I did a normal `cut` and it spit out 0.1.9

**Comment by getong** [comment]
The version number which is bigger might be the later.

**Comment by Licenser** [comment]
yes I know, for some reason `rebar3 hex cut` ignored `v0.2.0`

**Comment by Licenser** [comment]
it should be 0.2.2 now
